server:
  port: 8080

app:
  jwt:
    issuer: service-desk
    secret: ${APP_JWT_SECRET:3QxQ5LjPphGaZxVM2xvuPDVibED5A35H/7yRDrYwoZb9aNqJjuyB8s7egDfji8WGJVd+HlKrthUP94vjq10meQ==}
    access-ttl-min: 10
    refresh-ttl-days: 14

spring:
  application:
    name: service_desk

  web:
    cors:
      allowed-origin-patterns:
        - "http://localhost:*"
        - "http://127.0.0.1:*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/service_desk}
    username: ${SPRING_DATASOURCE_USERNAME:service_desk}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

logging:
  level:
    org.springframework.security: DEBUG